package model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseUser<M extends BaseUser<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setUsername(java.lang.String username) {
		set("username", username);
		return (M)this;
	}
	


	public M setPassword(java.lang.String  password) {
		set("password", password);
		return (M)this;
	}
	
	public byte[] getPassword() {
		return get("password");
	}

	public M setNickname(java.lang.String  nickname) {
		set("nickname", nickname);
		return (M)this;
	}
	
	public java.lang.String  getNickname() {

		return get("nickname");
	}

	public M setRole(java.lang.String  role) {
		set("role", role);
		return (M)this;
	}
	
	public java.lang.String  getRole() {
		return get("role");
	}

}
